config/routes.rb
Rails.application.routes.draw do

  resources :working_operations
  resources :boost_vib_ls_inds
  resources :local_vib_s_indicators
  resources :boost_vib_l_inds
  resources :local_vib_f_indicators
  resources :boost_vibro_indicators
  resources :total_vibration_indicators
  resources :noise_indicators
  resources :staff_workers
  resources :sensors
  resources :measurement_gauges
  resources :register_signals
  resources :control_tools
  resources :workpoints
  resources :workplaces
  resources :subdivisions
  resources :companies
  root 'people#index'

  resources :people do
    member do
      get 'heart_rate'
      get 'ad'
      get 'spirometr'
      get 'glucometr'
      get 'weigher'
      get 'vibrotester'
      get 'audiometer'
    end
  end
  devise_for :users

end

app/models/workpoint.rb
class Workpoint < ActiveRecord::Base
  belongs_to :workplace
  mount_uploader :description_file, DescriptionUploader
  validates :name, :description, :type_vpf, :workplace, presence: true
  validates :number_id,  length: {in: 2..2}
end

app/controllers/workpoints_controller.rb
class WorkpointsController < ApplicationController
  before_action :set_workpoint, only: [:show, :edit, :update, :destroy]

  # GET /workpoints
  # GET /workpoints.json
  def index
    @q = Workpoint.eager_load(:workplace => {:subdivision => :company}).ransack(params[:q])
    @workpoints = @q.result(distinct: true)
    # @workpoints = Workpoint.all
  end

  # GET /workpoints/1
  # GET /workpoints/1.json
  def show
  end

  # GET /workpoints/new
  def new
    @workpoint = Workpoint.new
  end

  # GET /workpoints/1/edit
  def edit
  end

  # POST /workpoints
  # POST /workpoints.json
  def create
    @workpoint = Workpoint.new(workpoint_params)
    @workpoint.uniq_number_id = "#{Company.where(id: Subdivision.where(id: Workplace.find(@workpoint.workplace_id).subdivision_id).last.company_id).last.number_id}" + "#{Subdivision.where(id: Workplace.find(@workpoint.workplace_id).subdivision_id).last.number_id}" + "#{Workplace.find(@workpoint.workplace_id).number_id}" + "#{@workpoint.number_id}"
    respond_to do |format|
      if @workpoint.save
        format.html { redirect_to @workpoint, notice: 'Данные сохранены' }
        format.json { render :show, status: :created, location: @workpoint }
      else
        format.html { render :new }
        format.json { render json: @workpoint.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workpoints/1
  # PATCH/PUT /workpoints/1.json
  def update
    respond_to do |format|
      if @workpoint.update(workpoint_params)
        format.html { redirect_to @workpoint, notice: 'Данные сохранены' }
        format.json { render :show, status: :ok, location: @workpoint }
      else
        format.html { render :edit }
        format.json { render json: @workpoint.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workpoints/1
  # DELETE /workpoints/1.json
  def destroy
    @workpoint.destroy
    respond_to do |format|
      format.html { redirect_to workpoints_url, notice: 'Workpoint was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workpoint
      @workpoint = Workpoint.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def workpoint_params
      params.require(:workpoint).permit(:name, :description, :type_vpf, :workplace_id, :description_file, :number_id, :uniq_number_id)
    end
end

app/views/workpoints/_form.html.haml
= simple_form_for @workpoint, html: { class: 'col-md-6 col-md-offset-3 text-center', role: 'form1' } do |f|

  .row.col-md-offset-3
    .col-md-8
      .form-group
        = f.input :number_id
    .col-md-8
      .form-group
        = f.input :name
    .col-md-8
      .form-group
        = f.input :description
  .row.col-md-offset-3
    .col-md-8
      .form-group
        = f.input :type_vpf, collection: ["Общая вибрация","Локальная вибрация","Шум и инфразвук"]
    .col-md-8
      .form-group
        = f.input :description_file
    .col-md-8
      .form-group
        = f.association :workplace, collection: Workplace.all.map{|x| [x.id, x.id]}
        -# = f.input :kind_of_action


  %br/

  .form-actions
    = link_to "Назад", Workpoint,  class: 'btn btn-primary'
    = f.submit 'Сохранить', class: 'btn btn-primary'

app/views/workpoints/edit.html.haml
.page-header.text-center
  %h1= t('headers.workpoints.edit')
= render 'form'

app/views/workpoints/index.html.haml
.page-header.text-center
  %h1= t('headers.workpoints.index')
= link_to new_workpoint_path, class: 'btn btn-success' do
  = fa_icon :plus
  = "Создать рабочую точку"
%table.table.table-hover
  %caption
= search_form_for @q , html: { class: 'form-inline form-inline-search form-inline-5 text-center', role: 'form' } do |f|
  = f.search_field 'workplace_subdivision_company_name_eq', class: 'form-control', placeholder: "Предприятие"
  = f.search_field 'workplace_subdivision_name_eq', class: 'form-control', placeholder: "Подразделение"
  = f.search_field 'workplace_name_eq', class: 'form-control', placeholder: "Рабочее место"
  -# = f.search_field 'last_visit_eq', class: 'form-control', placeholder: "Дата формата дд.мм.гггг"

  %br
  %br
  .inline.text-center
    = f.submit 'Поиск', class: 'btn btn-primary'
    = link_to 'Сбросить', workpoints_path, class: 'btn btn-default'
%br
%br

%table.table.table-hover.sortable
  %thead
    %tr
      %th= Workpoint.human_attribute_name :uniq_number_id
      %th= Workpoint.human_attribute_name :number_id
      %th= "Предприятие"
      %th= "Подразделение"
      %th= Workpoint.human_attribute_name :workplace
      %th= Workpoint.human_attribute_name :name
      %th= Workpoint.human_attribute_name :description
      %th= Workpoint.human_attribute_name :type_vpf
      %th
      %th
      %th

  %tbody
    - @workpoints.each do |workpoint|
      %tr.tr-href{data: {link: workpoint_path(workpoint)}}
        %td= workpoint.uniq_number_id.present? ? workpoint.uniq_number_id : " "
        %td= workpoint.number_id.present? ? workpoint.number_id : " "
        %td= workpoint.workplace.subdivision.company.name
        %td= workpoint.workplace.subdivision.name
        %td= workpoint.workplace.name.present? ? workpoint.workplace.name : workpoint.workplace.id
        %td= workpoint.name
        %td= workpoint.description
        %td= workpoint.type_vpf
        %td
          = link_to workpoint, class: 'btn btn-success' do
            = fa_icon :eye
        %td
          = link_to edit_workpoint_path(workpoint), class: 'btn btn-info' do
            = fa_icon :edit
        %td
          = link_to workpoint, :method => :delete, :data => { :confirm => t('helpers.sure') }, class: 'btn btn-danger' do
            = fa_icon :times

app/views/workpoints/new.html.haml
.page-header.text-center
  %h1= t('headers.workpoints.new')
= render 'form'

app/views/workpoints/show.html.haml
.page-header.text-center
  %h1= t('headers.workpoints.show')
%br/
%br/
%dl
  .well.col-md-12
    .row
      .col-md-2
        %dt= Workpoint.human_attribute_name(:name)
        %dd= @workpoint.name
      .col-md-2
        %dt= Workpoint.human_attribute_name(:description)
        %dd= @workpoint.description
      .col-md-2
        %dt= Workpoint.human_attribute_name(:description_file)
        %dd= @workpoint.description_file? ? (link_to "#{@workpoint.description_file.file.filename}", @workpoint.description_file.url ,target: '_blank') : "Файл отсутствует"

    .row
      .col-md-2
        %dt= Workpoint.human_attribute_name(:type_vpf)
        %dd= @workpoint.type_vpf
      .col-md-2
        %dt= Workpoint.human_attribute_name(:workplace)
        %dd= @workpoint.workplace.id


.text-center
  %br/
  %br/
  = link_to 'К кспику рабочих точек', workpoints_path, class: 'btn btn-primary btn-sm'
  = link_to 'Изменить', edit_workpoint_path(@workpoint), class: 'btn btn-primary btn-sm'