config/routes.rb
Rails.application.routes.draw do

  resources :working_operations
  resources :boost_vib_ls_inds
  resources :local_vib_s_indicators
  resources :boost_vib_l_inds
  resources :local_vib_f_indicators
  resources :boost_vibro_indicators
  resources :total_vibration_indicators
  resources :noise_indicators
  resources :staff_workers
  resources :sensors
  resources :measurement_gauges
  resources :register_signals
  resources :control_tools
  resources :workpoints
  resources :workplaces
  resources :subdivisions
  resources :companies
  root 'people#index'

  resources :people do
    member do
      get 'heart_rate'
      get 'ad'
      get 'spirometr'
      get 'glucometr'
      get 'weigher'
      get 'vibrotester'
      get 'audiometer'
    end
  end
  devise_for :users

end

app/models/workplace.rb
class Workplace < ActiveRecord::Base
  belongs_to :subdivision
  validates  :type_vpf,:shift_duration, :number_of_shift, :subdivision, :name, presence: true
  validates :shift_duration, numericality: {greater_than_or_equal_to: 0 }
  validates :shift_duration, numericality: {less_than_or_equal_to: 24 }
  validates :number_of_shift, numericality: {greater_than_or_equal_to: 1 }
  validates :number_of_shift, numericality: {less_than_or_equal_to: 6 }
  validates :number_id,  length: {in: 2..2}
end

app/controllers/workplaces_controller.rb
class WorkplacesController < ApplicationController
  before_action :set_workplace, only: [:show, :edit, :update, :destroy]

  # GET /workplaces
  # GET /workplaces.json
  def index
    @q = Workplace.eager_load(:subdivision => :company).ransack(params[:q])
    @workplaces = @q.result(distinct: true)
  end

  # GET /workplaces/1
  # GET /workplaces/1.json
  def show
  end

  # GET /workplaces/new
  def new
    @workplace = Workplace.new
  end

  # GET /workplaces/1/edit
  def edit
  end

  # POST /workplaces
  # POST /workplaces.json
  def create
    @workplace = Workplace.new(workplace_params)

    respond_to do |format|
      if @workplace.save
        format.html { redirect_to @workplace, notice: 'Данные сохранены' }
        format.json { render :show, status: :created, location: @workplace }
      else
        format.html { render :new }
        format.json { render json: @workplace.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workplaces/1
  # PATCH/PUT /workplaces/1.json
  def update
    respond_to do |format|
      if @workplace.update(workplace_params)
        format.html { redirect_to @workplace, notice: 'Данные сохранены' }
        format.json { render :show, status: :ok, location: @workplace }
      else
        format.html { render :edit }
        format.json { render json: @workplace.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workplaces/1
  # DELETE /workplaces/1.json
  def destroy
    @workplace.destroy
    respond_to do |format|
      format.html { redirect_to workplaces_url, notice: 'Workplace was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workplace
      @workplace = Workplace.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def workplace_params
      params.require(:workplace).permit(:type_vpf, :shift_duration, :number_of_shift, :subdivision_id, :number_id, :name)
    end
end

app/views/workplaces/_form.html.haml
= simple_form_for @workplace, html: { class: 'col-md-6 col-md-offset-3 text-center', role: 'form1' } do |f|

  .row.col-md-offset-3
    .col-md-8
      .form-group
        = f.input :name
    .col-md-8
      .form-group
        = f.input :number_id
    .col-md-8
      .form-group
        = f.input :type_vpf, collection: ["Транспортная","Технологическая","Транспортно-технологическая"]
    .col-md-8
      .form-group
        = f.input :shift_duration
  .row.col-md-offset-3
    .col-md-8
      .form-group
        = f.input :number_of_shift
    .col-md-8
      .form-group
        = f.association :subdivision
        -# = f.input :kind_of_action


  %br/

  .form-actions
    = link_to "Назад", Workplace,  class: 'btn btn-primary'
    = f.submit 'Сохранить', class: 'btn btn-primary'

app/views/workplaces/edit.html.haml
.page-header.text-center
  %h1= t('headers.workplaces.edit')
= render 'form'

app/views/workplaces/index.html.haml
.page-header.text-center
  %h1= t('headers.workplaces.index')
= link_to new_workplace_path, class: 'btn btn-success' do
  = fa_icon :plus
  = "Создать рабочее место"
%table.table.table-hover
  %caption
= search_form_for @q , html: { class: 'form-inline form-inline-search form-inline-5 text-center', role: 'form' } do |f|
  = f.search_field 'subdivision_company_name_eq', class: 'form-control', placeholder: "Предприятие"
  = f.search_field 'subdivision_name_eq', class: 'form-control', placeholder: "Подразделение"
  -# = f.search_field 'last_visit_eq', class: 'form-control', placeholder: "Дата формата дд.мм.гггг"

  %br
  %br
  .inline.text-center
    = f.submit 'Поиск', class: 'btn btn-primary'
    = link_to 'Сбросить', workplaces_path, class: 'btn btn-default'
%br
%br

%table.table.table-hover.sortable
  %thead
    %tr
      %th= Workplace.human_attribute_name :number_id
      %th= "Предприятие"
      %th= Workplace.human_attribute_name :subdivision
      %th= Workplace.human_attribute_name :name
      %th= Workplace.human_attribute_name :type_vpf
      %th= Workplace.human_attribute_name :shift_duration
      %th= Workplace.human_attribute_name :number_of_shift

      %th
      %th
      %th

  %tbody
    - @workplaces.each do |workplace|
      %tr.tr-href{data: {link: workplace_path(workplace)}}
        %td= workplace.number_id.present? ? workplace.number_id : " "
        %td= workplace.subdivision.company.name
        %td= workplace.subdivision.name
        %td= workplace.name.present? ?  workplace.name : " "
        %td= workplace.type_vpf
        %td= workplace.shift_duration
        %td= workplace.number_of_shift

        %td
          = link_to workplace, class: 'btn btn-success' do
            = fa_icon :eye
        %td
          = link_to edit_workplace_path(workplace), class: 'btn btn-info' do
            = fa_icon :edit
        %td
          = link_to workplace, :method => :delete, :data => { :confirm => t('helpers.sure') }, class: 'btn btn-danger' do
            = fa_icon :times

app/views/workplaces/new.html.haml
.page-header.text-center
  %h1= t('headers.workplaces.new')
= render 'form'

app/views/workplaces/show.html.haml
.page-header.text-center
  %h1= t('headers.workplaces.show')
%br/
%br/
%dl
  .well.col-md-12
    .row
      .col-md-2
        %dt= Workplace.human_attribute_name(:type_vpf)
        %dd= @workplace.type_vpf
      .col-md-2
        %dt= Workplace.human_attribute_name(:shift_duration)
        %dd= @workplace.shift_duration
    .row
      .col-md-2
        %dt= Workplace.human_attribute_name(:number_of_shift)
        %dd= @workplace.number_of_shift
      .col-md-2
        %dt= Workplace.human_attribute_name(:subdivision)
        %dd= @workplace.subdivision.name


.text-center
  %br/
  %br/
  = link_to 'К кспику рабочих мест', workplaces_path, class: 'btn btn-primary btn-sm'
  = link_to 'Изменить', edit_subdivision_path(@workplace), class: 'btn btn-primary btn-sm'