config/routes.rb
Rails.application.routes.draw do

  resources :working_operations
  resources :boost_vib_ls_inds
  resources :local_vib_s_indicators
  resources :boost_vib_l_inds
  resources :local_vib_f_indicators
  resources :boost_vibro_indicators
  resources :total_vibration_indicators
  resources :noise_indicators
  resources :staff_workers
  resources :sensors
  resources :measurement_gauges
  resources :register_signals
  resources :control_tools
  resources :workpoints
  resources :workplaces
  resources :subdivisions
  resources :companies
  root 'people#index'

  resources :people do
    member do
      get 'heart_rate'
      get 'ad'
      get 'spirometr'
      get 'glucometr'
      get 'weigher'
      get 'vibrotester'
      get 'audiometer'
    end
  end
  devise_for :users

end

app/models/working_operation.rb
class WorkingOperation < ActiveRecord::Base
  belongs_to :staff_worker
  has_many :noise_indicators
  has_many :local_vib_f_indicators
  has_many :local_vib_s_indicators
  has_many :total_vibration_indicators
end

app/controllers/working_operations_controller.rb
class WorkingOperationsController < ApplicationController
  before_action :set_working_operation, only: [:show, :edit, :update, :destroy]

  # GET /working_operations
  # GET /working_operations.json
  def index
    @working_operations = WorkingOperation.all
  end

  # GET /working_operations/1
  # GET /working_operations/1.json
  def show
  end

  # GET /working_operations/new
  def new
    @working_operation = WorkingOperation.new
  end

  # GET /working_operations/1/edit
  def edit
  end

  # POST /working_operations
  # POST /working_operations.json
  def create
    @working_operation = WorkingOperation.new(working_operation_params)
    respond_to do |format|
      if @working_operation.save
        format.html { redirect_to staff_worker_path(@working_operation.staff_worker_id), notice: 'Данные сохранены' }
        format.json { render :show, status: :created, location: @working_operation }
      else
        format.html { render :new }
        format.json { render json: @working_operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /working_operations/1
  # PATCH/PUT /working_operations/1.json
  def update
    respond_to do |format|
      if @working_operation.update(working_operation_params)
        format.html { redirect_to @working_operation, notice: 'Working operation was successfully updated.' }
        format.json { render :show, status: :ok, location: @working_operation }
      else
        format.html { render :edit }
        format.json { render json: @working_operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /working_operations/1
  # DELETE /working_operations/1.json
  def destroy
    @working_operation.destroy
    respond_to do |format|
      format.html { redirect_to working_operations_url, notice: 'Working operation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_working_operation
      @working_operation = WorkingOperation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def working_operation_params
      params.require(:working_operation).permit(:staff_worker_id, :date_of_operation, :duration_shift)
    end
end

app/views/working_operations/_form.html.haml
= simple_form_for @working_operation, html: { class: 'col-md-6 col-md-offset-3 text-center', role: 'form1' } do |f|
  .row.col-md-offset-3
    .col-md-8
      .form-group
        = datepicker_field(f, :date_of_operation)

  .row.col-md-offset-3
    .col-md-8
      .form-group
        =f.input :duration_shift
        =f.input :staff_worker_id, as: :hidden, input_html: {value: params[:worker_id]}

  %br/

  .form-actions
    = link_to "Назад", staff_worker_path(params[:worker_id]),  class: 'btn btn-primary'
    = f.submit 'Сохранить', class: 'btn btn-primary'

app/views/working_operations/edit.html.haml
%h1 Editing working_operation

= render 'form'

= link_to 'Show', @working_operation
\|
= link_to 'Back', working_operations_path

app/views/working_operations/index.html.haml
%h1 Listing working_operations

%table
  %thead
    %tr
      %th Staf worker
      %th Date of operation
      %th Duration shift
      %th
      %th
      %th

  %tbody
    - @working_operations.each do |working_operation|
      %tr
        %td= working_operation.staf_worker
        %td= working_operation.date_of_operation
        %td= working_operation.duration_shift
        %td= link_to 'Show', working_operation
        %td= link_to 'Edit', edit_working_operation_path(working_operation)
        %td= link_to 'Destroy', working_operation, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Working operation', new_working_operation_path

app/views/working_operations/new.html.haml
.page-header.text-center
  %h1= "Рабочая операция"
= render 'form'