config/routes.rb
Rails.application.routes.draw do

  resources :working_operations
  resources :boost_vib_ls_inds
  resources :local_vib_s_indicators
  resources :boost_vib_l_inds
  resources :local_vib_f_indicators
  resources :boost_vibro_indicators
  resources :total_vibration_indicators
  resources :noise_indicators
  resources :staff_workers
  resources :sensors
  resources :measurement_gauges
  resources :register_signals
  resources :control_tools
  resources :workpoints
  resources :workplaces
  resources :subdivisions
  resources :companies
  root 'people#index'

  resources :people do
    member do
      get 'heart_rate'
      get 'ad'
      get 'spirometr'
      get 'glucometr'
      get 'weigher'
      get 'vibrotester'
      get 'audiometer'
    end
  end
  devise_for :users

end

app/models/staff_worker.rb
class StaffWorker < ActiveRecord::Base
  belongs_to :subdivision
  belongs_to :workplace
  belongs_to :additional_workplace, class_name: "Workplace"
  validates :number_id,  length: {in: 10..10}
  def full_name
    "#{surname} #{name} #{patronymic}"
  end
end

app/controllers/staff_workers_controller.rb
class StaffWorkersController < ApplicationController
  before_action :set_staff_worker, only: [:show, :edit, :update, :destroy]

  # GET /staff_workers
  # GET /staff_workers.json
  def index
    @q = StaffWorker.eager_load(:subdivision => :company).ransack(params[:q])
    @staff_workers = @q.result(distinct: true)
    # @staff_workers = StaffWorker.all
  end

  # GET /staff_workers/1
  # GET /staff_workers/1.json
  def show
    @noise_indicators = NoiseIndicator.where(staff_worker_id: @staff_worker.id)
    @total_vibration_indicators = TotalVibrationIndicator.where(staff_worker_id: @staff_worker.id)
    @local_vib_f_indicators =  LocalVibFIndicator.where(staff_worker_id: @staff_worker.id)
    @local_vib_s_indicators =  LocalVibSIndicator.where(staff_worker_id: @staff_worker.id)
    @working_operations  = WorkingOperation.where(staff_worker_id: @staff_worker.id)
  end

  # GET /staff_workers/new
  def new
    @staff_worker = StaffWorker.new
  end

  def result_control
    @staff_worker = StaffWorker.find(params[:id])
    @noise_indicators = NoiseIndicator.where(staff_worker_id: @staff_worker.id)
    @total_vibration_indicators = TotalVibrationIndicator.where(staff_worker_id: @staff_worker.id)
    @local_vib_f_indicators =  LocalVibFIndicator.where(staff_worker_id: @staff_worker.id)
    @local_vib_s_indicators =  LocalVibSIndicator.where(staff_worker_id: @staff_worker.id)
    @working_operations  = WorkingOperation.where(staff_worker_id: @staff_worker.id)
  end

  # GET /staff_workers/1/edit
  def edit
  end

  # POST /staff_workers
  # POST /staff_workers.json
  def create
    @staff_worker = StaffWorker.new(staff_worker_params)

    respond_to do |format|
      if @staff_worker.save
        format.html { redirect_to @staff_worker, notice: 'Данные сохранены' }
        format.json { render :show, status: :created, location: @staff_worker }
      else
        format.html { render :new }
        format.json { render json: @staff_worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /staff_workers/1
  # PATCH/PUT /staff_workers/1.json
  def update
    respond_to do |format|
      if @staff_worker.update(staff_worker_params)
        format.html { redirect_to @staff_worker, notice: 'Данные сохранены' }
        format.json { render :show, status: :ok, location: @staff_worker }
      else
        format.html { render :edit }
        format.json { render json: @staff_worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /staff_workers/1
  # DELETE /staff_workers/1.json
  def destroy
    @staff_worker.destroy
    respond_to do |format|
      format.html { redirect_to staff_workers_url, notice: 'Staff worker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_staff_worker
      @staff_worker = StaffWorker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def staff_worker_params
      params.require(:staff_worker).permit(:name, :surname, :patronymic, :number_id, :subdivision_id, :birthday, :position, :duration_work, :labor_activity_type, :labor_activity_category, :duration_one_shift, :workplace_id, :work_in_workplace, :description_operation,:additional_workplace_id, :additional_work_in_workplace, :additional_description_operation)
    end
end

app/views/staff_workers/_form.html.haml
= simple_form_for @staff_worker, html: { class: 'col-md-6 col-md-offset-3 text-center', role: 'form1' } do |f|

  .row.col-md-offset-3
    .col-md-8
      .form-group
        = f.input :number_id
    .col-md-8
      .form-group
        = f.input :surname
    .col-md-8
      .form-group
        = f.input :name

  .row.col-md-offset-3
    .col-md-8
      .form-group
        = f.input :patronymic
    .col-md-8
      .form-group
        = f.association :subdivision
  .row.col-md-offset-3
    .col-md-8
      .form-group
        = datepicker_field(f, :birthday)
    .col-md-8
      .form-group
        = f.input :position
    .col-md-8
      .form-group
        = datepicker_field(f, :duration_work)
  .row.col-md-offset-3

  .row.col-md-offset-3
    .col-md-8
      .form-group
        = f.input :labor_activity_type
    .col-md-8
      .form-group
        = f.input :labor_activity_category
  .row.col-md-offset-3
    .col-md-8
      .form-group
        = f.input :duration_one_shift
  .row.col-md-offset-3
    .col-md-8
      .form-group
        = f.association :workplace, collection: Workplace.all.map{|x| [x.id, x.id]}
    .col-md-8
      .form-group
        = f.input :work_in_workplace
  .row.col-md-offset-3
    .col-md-8
      .form-group
        = f.input :description_operation
  .row.col-md-offset-3
    .col-md-8
      .form-group
        = f.association :additional_workplace, collection: Workplace.all.map{|x| [x.id, x.id]}
    .col-md-8
      .form-group
        = f.input :additional_work_in_workplace
  .row.col-md-offset-3
    .col-md-8
      .form-group
        = f.input :additional_description_operation
        -# = f.input :kind_of_action


  %br/

  .form-actions
    - if params[:id].present?
      = link_to "Назад", staff_worker_path,  class: 'btn btn-primary'
    - else
      = link_to "Назад", StaffWorker,  class: 'btn btn-primary'
    = f.submit 'Сохранить', class: 'btn btn-primary'

app/views/staff_workers/edit.html.haml
.page-header.text-center
  %h1= t('headers.staff_workers.edit')
= render 'form'

app/views/staff_workers/index.html.haml
.page-header
  %h1= t('headers.staff_workers.index')
= link_to new_staff_worker_path, class: 'btn btn-success' do
  = fa_icon :plus
  = "Добавить работника"
%table.table.table-hover
  %caption
= search_form_for @q , html: { class: 'form-inline form-inline-search form-inline-5 text-center', role: 'form' } do |f|
  = f.search_field 'subdivision_company_name_eq', class: 'form-control', placeholder: "Предприятие"
  = f.search_field 'subdivision_name_eq', class: 'form-control', placeholder: "Подразделение"
  -# = f.search_field 'last_visit_eq', class: 'form-control', placeholder: "Дата формата дд.мм.гггг"

  %br
  %br
  .inline.text-center
    = f.submit 'Поиск', class: 'btn btn-primary'
    = link_to 'Сбросить', staff_workers_path, class: 'btn btn-default'
%br
%br
%br

%table.table.table-hover.sortable
  %thead
    %tr
      %th= "Предприятие"
      %th= "Подразделение"
      %th= StaffWorker.human_attribute_name :full_name
      %th= StaffWorker.human_attribute_name :birthday
      %th= StaffWorker.human_attribute_name :position
      %th= StaffWorker.human_attribute_name :duration_work
      %th= StaffWorker.human_attribute_name :labor_activity_type
      %th= StaffWorker.human_attribute_name :labor_activity_category
      %th
      %th
      %th

  %tbody
    - @staff_workers.each do |staff_worker|
      %tr
        %td= staff_worker.subdivision.company.name
        %td= staff_worker.subdivision.name
        %td= staff_worker.surname + " " +  staff_worker.name + " " +   staff_worker.patronymic
        %td= l staff_worker.birthday, format: :default
        %td= staff_worker.position
        %td= l staff_worker.duration_work, format: :default
        %td= staff_worker.labor_activity_type
        %td= staff_worker.labor_activity_category

        %td
          = link_to staff_worker, class: 'btn btn-success' do
            = fa_icon :eye
        %td
          = link_to edit_staff_worker_path(staff_worker), class: 'btn btn-info' do
            = fa_icon :edit
        %td
          = link_to staff_worker, :method => :delete, :data => { :confirm => t('helpers.sure') }, class: 'btn btn-danger' do
            = fa_icon :times

app/views/staff_workers/new.html.haml
.page-header.text-center
  %h1= t('headers.staff_workers.new')
= render 'form'

app/views/staff_workers/result_control.html.haml
.col-md-10.col-md-offset-1
  .text-center
    %br/
    %br/
    %h3
      = "Рабочие операции"
      = link_to new_working_operation_path(worker_id: params[:id]), class: 'btn btn-success' do
        = fa_icon :plus
        = ""
  .row
    %table.table.table-hover
      %thead
        %tr
          %th{ colspan: 3 }= "Операции"
          %th{ colspan: 4 }= "Показатели шума"
          %th{ colspan: 4 }= "Показатели общей вибрации"
          %th{ colspan: 4 }= "Показатели локальной вибрации от источника 1"
          %th{ colspan: 4 }= "Показатели локальной вибрации от источника 2"
      %thead
        %tr
          %th= "ID операции"
          %th= "Дата операции"
          %th
          %th= "ID операции"
          %th= "Дата внесения данных"
          %th= NoiseIndicator.human_attribute_name :terms
          %th
          %th= "ID операции"
          %th= "Дата внесения данных"
          %th= NoiseIndicator.human_attribute_name :terms
          %th
          %th= "ID операции"
          %th= "Дата внесения данных"
          %th= NoiseIndicator.human_attribute_name :terms
          %th
          %th= "ID операции"
          %th= "Дата внесения данных"
          %th= NoiseIndicator.human_attribute_name :terms
          %th

      %tbody
        - @working_operations.each do |working_operation|
          %tr
            %td= working_operation.id
            %td= "#{l working_operation.date_of_operation.to_date, format: :default}"
            %td
              = link_to working_operation_path(working_operation), class: 'btn btn-success' do
                = fa_icon :eye
            - if working_operation.noise_indicators.present?
              - working_operation.noise_indicators.each do |ni|
                %td= ni.id
                %td= "#{l ni.created_at.to_date, format: :default}"
                %td= ni.terms
                %td
                  = link_to ni, class: 'btn btn-success' do
                    = fa_icon :eye
            - else
              %td.text-center{ colspan: 4 }
                = link_to new_noise_indicator_path(worker_id: params[:id], operation_id: working_operation.id), class: 'btn btn-default' do
                  = fa_icon :plus
                  = "Добавить показатели шума"
            - if working_operation.total_vibration_indicators.present?
              - working_operation.total_vibration_indicators.each do |ni|
                %td= ni.id
                %td= "#{l ni.created_at.to_date, format: :default}"
                %td= ni.terms
                %td
                  = link_to ni, class: 'btn btn-success' do
                    = fa_icon :eye
            - else
              %td.text-center{ colspan: 4 }
                = link_to new_total_vibration_indicator_path(worker_id: params[:id], operation_id: working_operation.id), class: 'btn btn-default' do
                  = fa_icon :plus
                  = "Добавить показатели общей вибрации"
            - if working_operation.local_vib_f_indicators.present?
              - working_operation.local_vib_f_indicators.each do |ni|
                %td= ni.id
                %td= "#{l ni.created_at.to_date, format: :default}"
                %td= ni.terms
                %td
                  = link_to ni, class: 'btn btn-success' do
                    = fa_icon :eye
            - else
              %td.text-center{ colspan: 4 }
                = link_to new_local_vib_f_indicator_path(worker_id: params[:id], operation_id: working_operation.id), class: 'btn btn-default' do
                  = fa_icon :plus
                  = "Добавить показатели локальной вибрации ИСТ1"
            - if working_operation.local_vib_s_indicators.present?
              - working_operation.local_vib_s_indicators.each do |ni|
                %td= ni.id
                %td= "#{l ni.created_at.to_date, format: :default}"
                %td= ni.terms
                %td
                  = link_to ni, class: 'btn btn-success' do
                    = fa_icon :eye
            - else
              %td.text-center{ colspan: 4 }
                = link_to new_local_vib_s_indicator_path(worker_id: params[:id], operation_id: working_operation.id), class: 'btn btn-default' do
                  = fa_icon :plus
                  = "Добавить показатели локальной вибрации ИСТ2"
  .text-center
    %br/
    %br/
    = link_to 'К кспику работников', staff_workers_path, class: 'btn btn-primary btn-sm'
    = link_to 'Назад', staff_worker_path(@staff_worker), class: 'btn btn-primary btn-sm'

app/views/staff_workers/show.html.haml
.page-header
  %h3= "Работник - #{@staff_worker.surname} #{@staff_worker.name} #{@staff_worker.patronymic}"
  %h3= "ID - #{@staff_worker.id}"
%br/
%br/
.col-md-6.col-md-offset-3
  .row
    %table.table.table-striped

      %tbody
        %tr
          %td= StaffWorker.human_attribute_name :full_name
          %td= @staff_worker.surname + " " + @staff_worker.name + " " +  @staff_worker.patronymic
        %tr
          %td= StaffWorker.human_attribute_name :subdivision
          %td= @staff_worker.subdivision.name
        %tr
          %td= StaffWorker.human_attribute_name :birthday
          %td= l @staff_worker.birthday, format: :default
        %tr
          %td= StaffWorker.human_attribute_name :position
          %td= @staff_worker.position
        %tr
          %td= StaffWorker.human_attribute_name :duration_work
          %td= l @staff_worker.duration_work, format: :default
        %tr
          %td= StaffWorker.human_attribute_name :labor_activity_type
          %td= @staff_worker.labor_activity_type
        %tr
          %td= StaffWorker.human_attribute_name :labor_activity_category
          %td= @staff_worker.labor_activity_category


        %tr
          %td= StaffWorker.human_attribute_name :duration_one_shift
          %td= @staff_worker.duration_one_shift
        %tr
          %td= StaffWorker.human_attribute_name :workplace
          %td= @staff_worker.workplace.id
        %tr
          %td= StaffWorker.human_attribute_name :work_in_workplace
          %td= @staff_worker.work_in_workplace
        %tr
          %td= StaffWorker.human_attribute_name :description_operation
          %td= @staff_worker.description_operation
        %tr
          %td= StaffWorker.human_attribute_name :additional_workplace
          %td= @staff_worker.additional_workplace.id
        %tr
          %td= StaffWorker.human_attribute_name :additional_work_in_workplace
          %td= @staff_worker.additional_work_in_workplace
        %tr
          %td= StaffWorker.human_attribute_name :additional_description_operation
          %td= @staff_worker.additional_description_operation

  .text-center
    %br/
    %br/
    = link_to 'К кспику работников', staff_workers_path, class: 'btn btn-primary btn-sm'
    = link_to 'Изменить', edit_staff_worker_path(@staff_worker), class: 'btn btn-primary btn-sm'
%br/
%br/
.col-md-10.col-md-offset-1
  .text-center
    %br/
    %br/
    = link_to 'Результат контроля ВПФ', result_control_staff_workers_path(id: @staff_worker.id), class: 'btn btn-primary btn-sm'
    = link_to 'Медицинские тригеры', staff_worker_path, class: 'btn btn-primary btn-sm'